#!/bin/bash

echo "🚀 Deploying Minimal Food Detection API (YOLO + ViT Only)"
echo "========================================================"

echo ""
echo "📋 Manual Deployment Steps for Render:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Select directory: food-analyzer-backend/python_models"
echo ""
echo "6. Configure the service:"
echo "   Name: food-detection-models"
echo "   Environment: Python"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: python app_minimal.py"
echo "   Plan: Free"
echo ""
echo "7. Add Environment Variables:"
echo "   FLASK_ENV=production"
echo "   PYTHONUNBUFFERED=1"
echo "   PORT=5000"
echo ""
echo "8. Click 'Create Web Service'"
echo ""
echo "🌐 Your service will be available at:"
echo "   https://food-detection-models.onrender.com"
echo ""
echo "🔗 Update your backend environment variable:"
echo "   PYTHON_MODELS_URL=https://food-detection-models.onrender.com"
echo ""
echo "🧪 Test after deployment:"
echo "   curl https://food-detection-models.onrender.com/health"
echo "   curl https://food-detection-models.onrender.com/models"
